export const CATEGORIES_ACTION_TYPES = {   
    FETCH_CATEGORIES_START: 'category/ETCH_CATEGORIES_START',
    FETCH_CATEGORIES_SUCCESS: 'category/ETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAILED: 'category/ETCH_CATEGORIES_FAILED',
}